server:
  port: 7001
eureka:
  instance:
    hostname: localhost1 #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否像eureka注册中心注册自己
    fetch-registry: false #表示如果为false，则表示为自己为注册中心
    service-url: #监控页面
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #单机
      defaultZone: http://localhost2:7002/eureka/,http://localhost3:7003/eureka/
#Eureka配置