server:
  port: 80
#Eureka配置
eureka:
  client:
    register-with-eureka: false #不像Eureka注册自己
    service-url:
      defaultZone: http://localhost1:7001/eureka/,http://localhost3:7002/eureka/,http://localhost3:7003/eureka/
