server:
  port: 8001

mybatis:
  type-aliases-package: com.niu.springcloud.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:Mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Ntj@13
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-hystrix-dept8001

#Eureka配置

#info配置
info:
  app.name: niu-springcloud
  company.name: blog.niu
